# Generated by Django 5.2 on 2025-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincrud', '0004_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
