# Generated by Django 5.2 on 2025-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincrud', '0007_alter_user_email_id_alter_user_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Examiner', 'Examiner'), ('Admin', 'Admin'), ('SME', 'SME')], max_length=50),
        ),
    ]
