# Generated by Django 5.2 on 2025-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincrud', '0008_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate'), ('Examiner', 'Examiner'), ('Admin', 'Admin'), ('SME', 'SME')], max_length=50),
        ),
    ]
