# Generated by Django 5.1.5 on 2025-05-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincrud', '0010_alter_user_email_id_alter_user_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('caption', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
